### ISSUE TITLE
Validate Requirements

### ISSUE THREAD

**Issue by IrynaMariukha** [IrynaMariukha/The_Repository#12]
- [ ] https://github.com/IrynaMariukha/The_Repository/issues/13
- [ ] https://github.com/IrynaMariukha/The_Repository/issues/14
- [ ] https://github.com/IrynaMariukha/The_Repository/issues/15
